# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Define environment variables
env:
  VERSION: "1.0.0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      #Print the "VERSION" variable value
      - name: Print the "VERSION" variable value
        run: echo ${{ vars.VERSION }}

      #Print the API_KEY secret
      - name: Print the API_KEY secret
        run: echo ${{ secrets.API_KEY }}

      #Create a sample file
      - name: Create a sample file
        run: echo "Hello World" > sample.txt

      # #Upload the sample file as an artifact
      # - name: Upload the sample file as an artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: sample-file
      #     path: ./sample.txt

      #List files in the current directory
      - name: List files in the current directory
        run: ls -al

      #Print PWD
      - name: Print PWD
        run: pwd

  job_2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Download the sample file artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: sample-file
      #     path: ./sample-file

      # #Print the content of the sample file
      # - name: Print the content of the sample file
      #   run: cat ./sample-file/sample.txt

      #List files in the current directory
      - name: List files in the current directory
        run: ls -al 